version: "3.8"

services:
  h2:
    build: .
    container_name: h2-server
    ports:
      - "1521:1521"
      - "9092:9092"
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -tcpPort 1521 -web -webAllowOthers -webPort 9092 -ifNotExists
    volumes:
      - ./data:/opt/h2-data
    restart: always